- hosts: localhost
  become: true
  vars_files:
    - variables/tlp.yml
    - variables/rpmfusion.yml 
    - variables/packer.yml
    - variables/java.yml  
    - variables/sync_files.yml
    - variables/conditionals.yml
    - variables/docker_compose.yml
    - variables/docker_ce.yml
    - variables/clamav.yml
    - variables/ghidra.yml
    - variables/setup_workspace.yml

  pre_tasks:
    - import_tasks: tasks/pre_tasks.yml

  roles:
    - role: robertdebock.tlp
    - role: robertdebock.rpmfusion
    - role: robertdebock.packer
    - role: robertdebock.java
    - role: robertdebock.docker_compose
    - role: robertdebock.docker_ce
    - role: robertdebock.clamav
    - role: ansible-role-ghidra

  tasks:
    - import_tasks: tasks/tasks.yml
  