---
- src: robertdebock.tlp
- src: robertdebock.rpmfusion
- src: robertdebock.packer
- src: robertdebock.java
- src: robertdebock.docker_compose
- src: robertdebock.docker_ce
- src: robertdebock.clamav
- src: https://github.com/scrool/ansible-role-ghidra
