- name: Append configurations to dnf.conf
  blockinfile:
    state: present
    insertafter: EOF
    dest: /etc/dnf/dnf.conf
    marker: "# ANSIBLE MANAGED BLOCK"
    content: |
      fastestmirror=1

- name: Append aliases to .bashrc
  become_user: "{{ owner }}"
  blockinfile:
    state: present
    insertafter: EOF
    dest: $HOME/.bashrc
    marker: "# ANSIBLE MANAGED BLOCK"
    content: |
      alias vim="vimx"
    owner: "{{ owner }}"
    group: "{{ group }}"