- name: Append configurations to dnf.conf
  blockinfile:
    state: present
    insertafter: EOF
    dest: /etc/dnf/dnf.conf
    marker: "# ANSIBLE MANAGED BLOCK"
    content: |
      fastestmirror=1

- name: Append configs to .bashrc
  become_user: "{{ owner }}"
  blockinfile:
    state: present
    insertafter: EOF
    dest: $HOME/.bashrc
    marker: "# ANSIBLE MANAGED BLOCK - ALIAS AND EXPORTS"
    content: |
      alias vim="nvim"
      eval "$(direnv hook bash)"
    owner: "{{ owner }}"
    group: "{{ group }}"

- name: Modify history environment variables
  become_user: "{{ owner }}"
  blockinfile:
    state: present
    insertafter: EOF
    dest: $HOME/.bashrc
    marker: "# ANSIBLE MANAGED BLOCK - ENVIRONMENT VARS"
    content: |
      # history
      export HISTTIMEFORMAT="%F %T"
      export HISTFILESIZE=5000

      # editor
      export EDITOR="nvim"
    owner: "{{ owner }}"
    group: "{{ group }}"
