---
- name: Install misc packages
  ansible.builtin.dnf:
    name:
      - rsync
      - direnv
      - poetry
      - uuid
      - util-linux-user
      - fish 
    state: latest

- name: Install the latest version of editors
  ansible.builtin.dnf:
    name:
      - vim
      - code
    state: latest

- name: Install the latest version of podman
  ansible.builtin.dnf:
    name: podman
    state: latest

- name: Install the latest version of vagrant
  ansible.builtin.dnf:
    name: vagrant
    state: latest

- name: Install the latest version of ripgrep
  ansible.builtin.dnf:
    name: ripgrep
    state: latest

- name: Install the latest version of virtualization packages
  ansible.builtin.dnf:
    name:
      - qemu
      - libvirt
      - wine
    state: latest

- name: Install the latest version of vlc
  ansible.builtin.dnf:
    name: vlc
    state: latest

- name: Install the latest version of group packages
  ansible.builtin.dnf:
    name:
      - "@Development Tools"
    state: latest

- name: Install some versions of python
  ansible.builtin.dnf:
    name:
      - python
      - python2
      - python37
      - python38
      - python39
      - python310
      - python311
    state: latest

- name: Install konsave python package
  ansible.builtin.pip:
    name: konsave
  when: kde | bool

- name: Install the latest version of Postman
  community.general.flatpak:
    name: com.getpostman.Postman
    state: present
