- name: Copy konsave configuration folder
  ansible.builtin.copy:
    src: ../files/konsave
    dest: "/home/{{ owner }}/.config"
    owner: "{{ owner }}"
    group: "{{ group }}"
  when: kde | bool

- name: Copy direnv configuration folder
  ansible.builtin.copy:
    src: ../files/direnv
    dest: "/home/{{ owner }}/.config"
    owner: "{{ owner }}"
    group: "{{ group }}"

- name: Copy neovim config to {{ owner }}
  ansible.builtin.file:
    src: ../files/nvim
    dest: "/home/{{ owner }}/.config"
    owner: "{{ owner }}"
    group: "{{ group }}"
    state: link

# It's nice to have the same config while I'm on root mode.
- name: Copy neovim config to root
  ansible.builtin.file:
    src: ../files/nvim
    dest: "/home/{{ owner }}/.config"
    owner: "root"
    group: "root"
    state: link

# TODO(r0x0d): Skip that if it is not i3 or dwm.
- name: Copy alacritty config
  ansible.builtin.file:
    src: ../files/alacritty.yml
    dest: "/home/{{ owner }}/.config/alacritty"
    owner: "{{ owner }}"
    group: "{{ group }}"
    state: link

- name: Clone alacritty-themes
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty-theme"
    dest: "/home/{{ owner }}/.config/alacritty/themes"

- name: Copy top-level .gitconfig
  ansible.builtin.copy:
    src: ../files/.gitconfig
    dest: "/home/{{ owner }}/.gitconfig"
    owner: "{{ owner }}"
    group: "{{ group }}"

- name: Copy personal .gitconfig
  ansible.builtin.copy:
    src: ../files/.gitconfig.personal
    dest: "/home/{{ owner }}/.gitconfig.extended"
    owner: "{{ owner }}"
    group: "{{ group }}"
  when: personal | bool

- name: Copy Red Hat .gitconfig
  ansible.builtin.copy:
    src: ../files/.gitconfig.redhat
    dest: "/home/{{ owner }}/.gitconfig.extended"
    owner: "{{ owner }}"
    group: "{{ group }}"
  when: redhat | bool

- name: Copy scripts to /usr/bin
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/usr/bin/{{ item.path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: u+x
  with_community.general.filetree: "../files/scripts/"
